---
- import_tasks: postgresql_install.yml
  tags:
    - postgresql

- import_tasks: postgresql_config.yml
  tags:
    - postgresql_config
    - postgresql
    - config

- name: "flush handlers"
  meta: flush_handlers
