---
- name: "Set max_connections = {{ postgresql_max_connections }}"
  lineinfile:
    path: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    regexp: '^max_connections'
    line: "max_connections = {{ postgresql_max_connections }}"
  notify: "restart postgresql"

- name: "Set TLS cert"
  when: postgresql_certificate_file is defined
  lineinfile:
    path: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    regexp: 'ssl_cert_file'
    line: "ssl_cert_file = '{{ postgresql_certificate_file }}'"
  notify: "restart postgresql"

- name: "Set TLS key"
  when: postgresql_certificate_key_file is defined
  lineinfile:
    path: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    regexp: 'ssl_key_file'
    line: "ssl_key_file = '{{ postgresql_certificate_key_file }}'"
  notify: "restart postgresql"

- name: "Set TLS CA chain"
  when: postgresql_certificate_chain_file is defined
  lineinfile:
    path: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    regexp: 'ssl_ca_file'
    line: "ssl_ca_file = '{{ postgresql_certificate_chain_file }}'"
  notify: "restart postgresql"

- name: "Create user {{ postgresql_db_user }} without superuser and createdb privileges"
  when: postgresql_db_user is defined and postgresql_db_user_password is defined
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ postgresql_db_user }}"
    password: "{{ postgresql_db_user_password }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    encrypted: yes
    state: present

- name: "Create database {{ postgresql_db_name }} owned by user {{ postgresql_db_user }}"
  when: postgresql_db_user is defined and postgresql_db_name is defined
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ postgresql_db_name }}"
    encoding: 'UTF-8'
    owner: "{{ postgresql_db_user }}"
    state: present

- name: "Create schema {{ postgresql_db_user }} in database {{ postgresql_db_name }}"
  when: postgresql_db_user is defined and postgresql_db_name is defined
  become: yes
  become_user: postgres
  postgresql_schema:
    database: "{{ postgresql_db_name }}"
    name: "{{ postgresql_db_user }}"
    owner: "{{ postgresql_db_user }}"
    state: present
