- name: "Install lsb-release"
  apt:
    name:
      - lsb-release

- name: "Add PostgreSQL Global Development Group (PGDG) repository key"
  apt_key:
    id: ACCC4CF8
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present

- name: "Add PGDG repository"
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename }}-pgdg main"
    filename: "pgdg"
    state: present

- name: "Install packages for Postgres {{ postgresql_version }}"
  package:
    name:
      - "postgresql-{{ postgresql_version }}"
      - "postgresql-client-{{ postgresql_version }}"
      - "python-psycopg2"
      - "python-ipaddress"
      - "libpq-dev"
      - "xz-utils"
      - "sudo"
    state: present

- name: "Hold postgresql package from upgrading"
  when: postgresql_hold_upgrades
  dpkg_selections:
    name: "postgresql-{{ postgresql_version }}"
    selection: hold

- name: "Create cron job for dumping data to a file usable for filesystem backup"
  when: postgresql_daily_backup
  cron:
    name: "Everyday do the backup of the PostgreSQL DB"
    cron_file: postgresql-backup
    hour: "22"
    minute: "50"
    user: postgres
    job: "umask 027 ; rm /var/lib/postgresql/backup.sql.xz ; /usr/bin/pg_dumpall | xz >/var/lib/postgresql/backup.sql.xz"

- name: "add rows to pg_hba.conf"
  postgresql_pg_hba:
    dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    contype: hostssl
    databases: all
    users: all
    address: all
    method: md5
  notify: "restart postgresql"