- name: "create /etc/apt/keyrings"
  file:
    state: directory
    path: /etc/apt/keyrings
    owner: root
    group: root
    mode: '0755'

- name: "add PostgreSQL Global Development Group (PGDG) repository key"
  get_url:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    dest: /etc/apt/keyrings/pgdg.asc
    force: false

- name: "clean old line without signed-by"
  lineinfile:
    path: /etc/apt/sources.list.d/pgdg.list
    line: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: absent

- name: "Add PGDG repository"
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/pgdg.asc] http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    filename: "pgdg"
    state: present

- name: "Install packages for Postgres {{ postgresql_version }}"
  package:
    name:
      - "postgresql-{{ postgresql_version }}"
      - "postgresql-client-{{ postgresql_version }}"
      - "python3-psycopg2"
      - "libpq-dev"
      - "zstd"
      - "sudo"
      - "cron"
    state: present

- name: "Hold postgresql package from upgrading"
  when: postgresql_hold_upgrades
  dpkg_selections:
    name: "postgresql-{{ postgresql_version }}"
    selection: hold

- name: "Create cron job for dumping data to a file usable for filesystem backup"
  when: postgresql_daily_backup
  cron:
    name: "Everyday do the backup of the PostgreSQL DB"
    cron_file: postgresql-backup
    hour: "{{ postgresql_daily_backup_hour | string }}"
    minute: "{{ postgresql_daily_backup_minute | string }}"
    user: postgres
    job: "umask 027 ; rm /var/lib/postgresql/backup.sql.zst ; /usr/bin/pg_dumpall | zstdmt -10 --quiet --force -o /var/lib/postgresql/backup.sql.zst{{ postgresql_daily_backup_more_commands }}"

- name: "create /var/lib/postgresql/dump_psql_db.sh file"
  copy:
    dest: /var/lib/postgresql/dump_psql_db.sh
    owner: postgres
    group: postgres
    mode: 0550
    content: |
      #!/bin/bash
      if [ -z "$1" ] ; then
        echo "Usage: $0 db_name"
        exit 1
      fi
      DBNAME="$1"
      FILENAME="$DBNAME"_`date +"%Y-%m-%d-%H-%M-%S"`.sql.zst
      echo "dumping PostgreSQL database $DBNAME into $PWD/$FILENAME ..."
      export LANG=cs_CZ.UTF-8
      umask 0027
      pg_dump $DBNAME | zstdmt -10 --quiet --force -o "$FILENAME"

- name: "add rows to pg_hba.conf"
  postgresql_pg_hba:
    dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    contype: hostssl
    databases: all
    users: all
    address: all
    method: md5
  notify: "restart postgresql"