---

- name: "allow listening on TCP port on all network interfaces"
  when: postgresql_allow_remote_connections
  become: yes
  become_user: postgres
  community.postgresql.postgresql_alter_system:
    param: listen_addresses
    value: '*'
  notify: "restart postgresql"

- name: "set settings using ALTER SYSTEM"
  become: yes
  become_user: postgres
  community.postgresql.postgresql_alter_system:
    param: "{{ item.key }}"
    value: "{{ item.value | string }}"
  notify: "restart postgresql"
  loop: "{{ postgresql_settings|dict2items }}"

- name: "Set TLS cert"
  when: postgresql_certificate_file is defined
  become: yes
  become_user: postgres
  community.postgresql.postgresql_alter_system:
    param: ssl_cert_file
    value: "{{ postgresql_certificate_file }}"
  notify: "restart postgresql"

- name: "Set TLS key"
  when: postgresql_certificate_key_file is defined
  become: yes
  become_user: postgres
  community.postgresql.postgresql_alter_system:
    param: ssl_key_file
    value: "{{ postgresql_certificate_key_file }}"
  notify: "restart postgresql"

- name: "Set TLS CA chain"
  when: postgresql_certificate_chain_file is defined
  become: yes
  become_user: postgres
  community.postgresql.postgresql_alter_system:
    param: ssl_ca_file
    value: "{{ postgresql_certificate_chain_file }}"
  notify: "restart postgresql"

