---
# handlers file for postgresql
- name: "restart postgresql"
  service:
    state: restarted
    name: "{{ servicename[ansible_os_family] }}"
  listen: "restart postgresql"
  vars:
    servicename:
      Debian: postgresql
      RedHat: postgresql-{{ postgresql_version }}
